### ISSUE TITLE
Result value of GhsPopComparisonRoads indicator is discrete instead of continuous 

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-api#191]
Should not be the result value continuous?

**Comment by Gigaszi** [comment]
Is there a particular reason why we do not calculate the result value in the same way as for the Buildings indicator? 
fraction = (self.feature_count_per_sqkm - yellow) / (green - yellow) * 0.5
self.result.value = 0.5 + fraction
