### ISSUE TITLE
Tests should use a fixed timerange

### ISSUE THREAD

**Issue by joker234** [GIScience/ohsome-quality-api#38]
Tests should be reproducible. But OQT currently allows the tests to produce different results depending on external resources (e.g. ohsome API). The results of the queries should not be changing only because the ohsome API covers a larger timerange. E.g. https://github.com/GIScience/ohsome-quality-analyst/commit/a2628e234d60c64bc537c67d8d6324cc3b33d5e5#diff-63f2f7efc0e30d4dd22cc038f27d3793beddbde215d954a961cd45dd2858f570L80-R80

**Comment by matthiasschaub** [comment]
That sound reasonable. That would mean to add an optional time parameter to every indicator/report. 
Another possibility could be to mock the `get_latest_ohsome_timestamp()` function of `ohsome/client.py` during tests to always return the same timestamp.
