### ISSUE TITLE
Define color palette for plots

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-api#591]

**Comment by mcauer** [comment]
Colors currently used in ohsome dashboard:
![image](https://github.com/GIScience/ohsome-quality-analyst/assets/2814068/9c885460-18ac-4a3f-8cc4-2dfb10406ca3)

**Comment by matthiasschaub** [comment]
After discussion, let's stick to what dashboard css theme provides.
@mcauer will add a list of colors and their hexcodes to this issue.

**Comment by mcauer** [comment]
These are the default colors of the Sematic UI CSS Framework:
```
/*---  Colors  ---*/
@red              : #DB2828;
@orange           : #F2711C;
@yellow           : #FBBD08;
@olive            : #B5CC18;
@green            : #21BA45;
@teal             : #00B5AD;
@blue             : #2185D0;
@violet           : #6435C9;
@purple           : #A333C8;
@pink             : #E03997;
@brown            : #A5673F;
@grey             : #767676;
@black            : #1B1C1D;
```
So for the currentness indicator we need: 

@red              : #DB2828;

@yellow           : #FBBD08;

@green            : #21BA45;
