### ISSUE TITLE
building-comparison: check eubucco coverage calculates with sea area

### ISSUE THREAD

**Issue by Gigaszi** [GIScience/ohsome-quality-api#732]
The function `get_eubucco_coverage_intersection_area` compares the area of the eubucco boundaries, which are on the coastline, with the dashboard bpolys, which are the sealine.

**Comment by hn437** [comment]
Due to this, the bpolys of states with lot's of coastline and islands like denmark is only covered by eubucco for less than 50%, eventhough the land mass is entirely covered. Due to the coverage of <50% the oqapi calculation is aborted
