### ISSUE TITLE
Deprecate/Discontinue the reports endpoint

### ISSUE THREAD

**Issue by mmerdes** [GIScience/ohsome-quality-api#816]
As of now, the only client for the `/reports` endpoint is the Sketchmap tool.
It is planned to disconnect the SMT from oqapi or move from using reports to indicators in oqapi.
In the future, a report-like functionality might be reimplemented.

Task:

* Remove `/reports` endpoint

**Comment by Gigaszi** [comment]
isnt this completed with #818 ?
