### ISSUE TITLE
Add new topic-specific attributes to backend metadata

### ISSUE THREAD

**Issue by mmerdes** [GIScience/ohsome-quality-api#826]
Currently, we support a number of topic-specific attributes in Oqapi.

The attributes described in the following document have to be translated to simple Ohsome filter expressions and added to the Oqapi metadata:

[2024_09_20_Topics Attributes Thematic Accuracy.pdf](https://github.com/user-attachments/files/17148990/2024_09_20_Topics.Attributes.Thematic.Accuracy.pdf)

**Background**

The attributes are defined using a simple subset of the Ohsome filter language,
which is described here:

https://github.com/GIScience/oshdb/tree/main/oshdb-filter#syntax

More information on OSM tags can be found here:

https://taginfo.openstreetmap.org

**Comment by mmerdes** [comment]
@JanReifenrath 
please use `dog_park` instead of `dog park`

**Comment by lenajossek** [comment]
Hi Matthias, wie per Mail besprochen hier das aktualisierte pdf, die Vorschläge für Anzeigenamen wurden eingefügt. 
Bitte beachte, dass ich die Attribute bei manchen Topics reduziert habe. Für manche Topics wurden bisher bewusst keine Attribute definiert, bezüglich dieser offenen Punkte würde ich gerne noch einmal mit Euch in Diskussion gehen. 

Lass mich gerne wissen, ob Rückfragen bestehen. 

Liebe Grüße und vielen Dank 

[2024_09_27_Topics Attributes Thematic Accuracy.pdf](https://github.com/user-attachments/files/17161235/2024_09_27_Topics.Attributes.Thematic.Accuracy.pdf)

**Comment by JanReifenrath** [comment]
### **Quality assurance of new attributes**
### _working new attributes:_
**Bus stops**
Bus stop area (low completeness of 37 out of 397016 in Germany)
Public transport platform

**Clinics**
Birthing centre 
Blood donation 
Rehabilitation 
Vaccination centre

**Fitness Centres**
Fitness 
Swimming 
Weightlifting (low completeness of 8 out of 44023 in Germany)

**Forests**
Private Access (low completeness of 85 out of 590459 in Germany)

**Kindergarten**
Playground

**Marketplace**
Winery

**Parks**
Commercial landuse (low completeness of 3 out of 45486 in Germany)
Theme park 
Greenfield (low completeness of 7 out of 45486 in Germany)
Playgorund

**School**
Playground

**Subway Station**
Tunnel 
Subway stop area
Public transport platform

**Supermarkets**
Parking (low completeness of 5 out of 33805 in Germany)

**Tram Stops**
Tram stop area (low completeness of 2 out of 10308 in Germany)
Public transport platform

### _problems with new attributes:_
**Forests**
Forestry: 0 matches found in Germany, Poland and France
Official access: 0 matches found in Germany, Poland and France
Track: 0 matches found in Germany and Poland and 1 match out of 567351 features in France
Forest boundary: 0 matches found in Germany and Poland

**Marketplace**
Bakery: 0 matches found in Germany and Poland
Handicraft: 0 matches found in Germany and Poland
Leather craft: 0 matches found in Germany and Poland
Shoemaker: 0 matches found in Germany and Poland

**Parks**
Dog Park: 0 matches found in Germany, Belgium and the Netherlands
Playgorund: 0 matches found in Germany, Poland, Belgium and the Netherlands

**School**
Playground: Topic School not found in Topics, Topic Schools does not have  Attribute Completeness indicator

**Subway Station**
Subway: 0 matches found in Germany, Poland and the Netherlands
Subway entrance: 0 matches found in Germany, Belgium and the Netherlands
Subway route: 0 matches found in Germany, Belgium and the Netherlands

**Supermarkets**
Convenience store: 0 matches found in Germany and the Netherlands
Beverages: 0 matches found in Germany and the Netherlands
Bicycle Parking: 0 matches found in Germany, Poland, the Netherlands and Belgium
Parking entrance: 0 matches found in Germany and the Netherlands
