### ISSUE TITLE
Make regression test suite less brittle

### ISSUE THREAD

**Issue by mmerdes** [GIScience/ohsome-quality-api#837]
Currently, the hurl tests in `/regression-tests` are too strongly coupled to the actual data values which change over time.

The goal of this issue is to use regular expressions to check the concrete numbers only roughly when matching the textual result description (`$.result[0].result.description`).
This will make the test suite more lenient with respect to changing OSM data.

For an example, see here:
https://github.com/GIScience/ohsome-quality-api/blob/main/regression-tests/roads_adminarea_roadcomparison.hurl

Background:
https://hurl.dev

**Comment by JanReifenrath** [comment]
@mmerdes i think after merging this issue could be closed
